contacts/urls.py
from django.urls import path
from .views import home, contacts, contact_list, contact_detail, create_list, create_contact, contact_groups

# app_name = 'contacts'

urlpatterns = [
    path('', home, name="home"),
    path('groups/', contact_groups, name='contact_groups'),
    path('contacts/', contacts, name="contacts"),
    path('groups/<int:id>', contact_list, name="contact_list"),
    path('contacts/<int:id>', contact_detail, name="contact_detail"),
    path('create_list', create_list, name="create_list"),
    path('create_contact', create_contact, name="create_contact"),
]

phonebook/urls.py
from django.contrib import admin
from django.urls import path, include
from register import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', v.register, name="register"),
    path('', include('contacts.urls')),
    path('', include('django.contrib.auth.urls')),
]

contacts/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class ContactList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="contactlist", null=True)
    name = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return self.name


class Contact(models.Model):
    contact_list = models.ForeignKey(ContactList, on_delete=models.CASCADE)
    name = models.CharField(max_length=20, unique=True)
    email = models.EmailField(unique=True)
    phone_number = models.IntegerField(unique=True)

    def __str__(self):
        return self.name

register/models.py
from django.db import models

# Create your models here.

contacts/forms.py
from django import forms
from .models import ContactList


class CreateNewList(forms.Form):
    name = forms.CharField(label="Name", max_length=20, required=True)


class CreateNewContact(forms.Form):
    contact_list = forms.ModelChoiceField(label="Contact List", queryset=ContactList.objects.all(), required=True)
    name = forms.CharField(label="Name", max_length=20, required=True)
    email = forms.EmailField(label="Email", required=True)
    phone_number = forms.IntegerField(label="Phone number", required=True)


# class SendEmailForm(forms.Form):
#     send_to = forms.EmailField(label="Send to:", max_length=50, required=True)
#     subject = forms.CharField(label="Subject", max_length=30, required=True)
#     message = forms.CharField(label="Message", max_length=500, widget=forms.Textarea)

register/forms.py
from django import forms
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    # TODO: validate if the inputed info is not repeated in the database
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

contacts/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import ContactList, Contact
from .forms import CreateNewList, CreateNewContact
from django.contrib.auth.decorators import login_required
from .tasks import send_email

# Create your views here.
login_url = '/login/'


def home(response):
    return render(response, 'home.html')


@login_required(login_url=login_url)
def contact_groups(response):
    groups = response.user.contactlist.all()
    context = {
        'groups': groups,
    }
    return render(response, 'contact_groups.html', context)


@login_required(login_url=login_url)
def contacts(response):
    # TODO: show only logged user's contacts
    all_contacts = Contact.objects.all()
    context = {
        'contacts': all_contacts,
    }
    return render(response, 'all_contacts.html', context)


@login_required(login_url=login_url)
def contact_list(response, id):
    # TODO: show list only to the owner
    contact_ls = ContactList.objects.get(id=id)

    if contact_ls in response.user.contactlist.all():
        context = {
            'contact_ls': contact_ls,
        }
        return render(response, 'contact_list.html', context)

    # TODO: verify this. Search about difference between this and redirect/httpredirect
    return render(response, 'registration/login.html')


@login_required(login_url=login_url)
def contact_detail(response, id):
    contact_det = Contact.objects.get(id=id)

    if response.user.contactlist.get(id=contact_det.contact_list.id):
        context = {
            'contact': contact_det,
        }
        return render(response, 'contact_item.html', context)

    # TODO: verify this. Search about difference between this and redirect/httpredirect
    return render(response, 'registration/login.html')


@login_required(login_url=login_url)
def create_list(response):
    form = CreateNewList()
    errors = []

    if response.method == 'POST':
        form = CreateNewList(response.POST)

        if form.is_valid():
            name_ = form.cleaned_data["name"]
            contact_list_ = ContactList(name=name_)
            try:
                contact_list_.save()
                response.user.contactlist.add(ls)

                return HttpResponseRedirect(f'groups/{contact_list_.id}')
            except Exception as e:
                print(e)
                errors.append('The name is already in use. Try another name.')

    context = {
        'form': form,
        'errors': errors,
    }

    return render(response, 'create_list.html', context)


@login_required(login_url=login_url)
def create_contact(response):
    form = CreateNewContact()
    errors = []

    if response.method == 'POST':
        form = CreateNewContact(response.POST)

        if form.is_valid():
            contact_list_ = form.cleaned_data["contact_list"]
            name_ = form.cleaned_data["name"]
            phone_number_ = form.cleaned_data["phone_number"]
            email_ = form.cleaned_data["email"]
            contact_ = Contact(contact_list=contact_list_, name=name_, phone_number=phone_number_, email=email_)
            try:
                contact_.save()
                send_email(contact=contact_, recipient=response.user.email)
                print('here')

                return HttpResponseRedirect(f'contacts/{contact_.id}')
            except Exception as e:
                print(e)
                errors.append('The contact seems to be already registered. Please verify the contact info.')

    context = {
        'form': form,
        'errors': errors,
    }

    return render(response, 'create_contact.html', context)

register/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm


# Create your views here.
def register(response):
    form = RegisterForm()

    if response.method == 'POST':
        form = RegisterForm(response.POST)
        if form.is_valid():
            # TODO: create an exception to handle the view if it rises an error
            form.save()

        return redirect("/")

    context = {
        'form': form,
    }

    return render(response, 'register/register.html', context)

templates/all_contacts.html
{% extends 'base.html' %}

{% block title %}
    All Contact
{% endblock %}

{% block content %}
    <h3>Contacts</h3>
    <hr>
    {% for contact in contacts %}
            <a href="{% url 'contact_detail' contact.id %}" class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">{{ contact.name }}</h5>
                </div>
                <p class="mb-1">{{ contact.phone_number }}</p>
                <small class="text-muted">{{ contact.email }}</small>
            </a>
        {% endfor %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>{% block title %}Phonebook{% endblock %}</title>
</head>

<body>

{% include 'components/navbar.html' %}

<div id="content" name="content">
    <div class="row justify-content-center">
        <div class="col-8">
            {% block content %}
                <p>Loading...</p>
            {% endblock %}
        </div>
    </div>
</div>

{% include 'components/footer.html' %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>


</html>

templates/components/footer.html
{# TODO: Create footer#}
<!-- Footer -->
<footer class="text-center text-lg-start bg-light text-muted">
  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2021 Copyright:
    <a class="text-reset fw-bold" href="https://www.linkedin.com/in/jsierrabravo/">Juanse, Inc. </a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

templates/components/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">PHONEBOOK</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">

            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'contact_groups' %}">Contact groups</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'contacts' %}">Contacts</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            Create
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <li><a class="dropdown-item" href="{% url 'create_list' %}">List of contacts</a></li>
                            <li><a class="dropdown-item" href="{% url 'create_contact' %}">Contact</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="/logout">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="/login">
                            <button class="btn btn-success">Login</button>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/contact_groups.html
{% extends 'base.html' %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    <h3>Contact Groups</h3>
    <hr>
    <div class="list-group">
        {% for group in groups %}
            <a href="{% url 'contact_list' group.id %}" class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">{{ group.name }}</h5>
                </div>
                <p class="mb-1">N contacts</p>
            </a>
        {% endfor %}
    </div>
{% endblock %}

templates/contact_item.html
{% extends 'base.html' %}

{% block title %}
    Contact
{% endblock %}

{% block content %}
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">{{ contact.name }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">{{ contact.phone_number }}</h6>
            <p class="card-text">{{ contact.email }}</p>
{#            TODO: add functionality to these buttons#}
            <a href="#" class="card-link text-reset fw-bold">Call</a>
            <a href="#" class="card-link text-reset fw-bold">Send email</a>
            <a href="#" class="card-link text-reset fw-bold">Edit</a>
            <a href="#" class="card-link text-reset fw-bold">Delete</a>
        </div>
    </div>
{% endblock %}

templates/contact_list.html
{% extends 'base.html' %}

{% block title %}
    Contact List
{% endblock %}

{% block content %}
    <h3>{{ contact_ls.name }}</h3>
    <hr>
        {% for contact in contact_ls.contact_set.all %}
            <a href="{% url 'contact_detail' contact.id %}" class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">{{ contact.name }}</h5>
                </div>
                <p class="mb-1">{{ contact.phone_number }}</p>
                <small class="text-muted">{{ contact.email }}</small>
            </a>
        {% endfor %}
{% endblock %}

templates/create_contact.html
{% extends 'base.html' %}

{% block title %}
    Create Contact
{% endblock %}

{% block content %}
    <h3>Create New Contact</h3>
    <hr>
    <form method="POST" action="{% url 'create_contact' %}" class="form-group">
        {% csrf_token %}
        {{ form.as_p }}
        {% for error in errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endfor %}
        <button type="submit" name="create" class="btn btn-success">Create Contact</button>
    </form>
{% endblock %}

templates/create_list.html
{% extends 'base.html' %}

{% block title %}
    Create Contact List
{% endblock %}

{% block content %}
    <h3>Create New List of Contacts</h3>
    <hr>
    <form method="POST" action="{% url 'create_list' %}" class="form-group">
        {% csrf_token %}
        {{ form.as_p }}
        {% for error in errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endfor %}
        <button type="submit" name="create" class="btn btn-success">Create List</button>
    </form>
{% endblock %}

templates/email_form.html
{% extends 'base.html' %}

{% block title %}
    Send Email
{% endblock %}

{% block content %}
    {{ form }}
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    <h3>Phonebook</h3>
    <hr>
    <p><strong>Phonebook</strong> is a web application that helps you to manage your contacts.</p>
    
{% endblock %}

templates/register/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Create an Account
{% endblock %}

{% block content %}
    <h3>Create an Account</h3>
    <hr>
    <form method="POST" action="" class="form-group">
        {% csrf_token %}
        {{ form|crispy }}
    <button type="submit" class="btn btn-success">Register</button>
    </form>

{% endblock %}